Add instructions for AUR package
SpyHoodle/PrideFetch pull request #14
Opened 2022-05-27 13:36 UTC by R0dn3yS

2022-05-28 16:39 UTC, SpyHoodle commented on README.md
> +from the AUR
Could we capitalize "from" and put an empty line before and after this line, like in "Running on NixOS" ?

2022-05-28 16:40 UTC, SpyHoodle requested changes
Ah, new to this 😬, didn't know this is where the button is  - check the comment I've left

2022-05-29 13:14 UTC, R0dn3yS commented
Should be good now

2022-05-29 15:29 UTC, SpyHoodle approved these changes

2022-05-29 15:29 UTC, merged